FROM ghcr.io/dockhippie/ubuntu:22.04-amd64@sha256:13b2bd7c97dcf20487ba641941fbea978b7fe7391ef99a79fa7ddd5512858a62

WORKDIR /var/lib/steam

RUN apt-get update -y && \
  apt-get upgrade -y && \
  apt-get install -y locales lib32gcc-s1 && \
  dpkg --add-architecture i386 && \
  locale-gen en_US.UTF-8 && \
  mkdir -p /var/lib/steam /var/log/steam && \
  groupadd -g 1000 steam && \
  useradd -u 1000 -d /var/lib/steam -g steam -s /bin/bash -M steam && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY ./overlay /

RUN curl http://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz | tar -C /var/lib/steam -xzf - && \
  chown -R steam:steam /var/lib/steam /var/log/steam && \
  steamcmd +login anonymous +quit && \
  rm -rf /var/lib/steam/Steam/logs && \
  ln -sf /var/log/steam /var/lib/steam/Steam/logs
