FROM ghcr.io/dockhippie/ubuntu:22.04-amd64@sha256:d84a6f9aa07b45d76f92da44d834bc51755784498eb1e0c78262b6dbf24a2165

WORKDIR /var/lib/steam

RUN apt-get update -y && \
  apt-get upgrade -y && \
  apt-get install -y locales lib32gcc-s1 && \
  dpkg --add-architecture i386 && \
  locale-gen en_US.UTF-8 && \
  mkdir -p /var/lib/steam /var/log/steam && \
  groupadd -g 1000 steam && \
  useradd -u 1000 -d /var/lib/steam -g steam -s /bin/bash -M steam && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY ./overlay /

RUN curl http://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz | tar -C /var/lib/steam -xzf - && \
  chown -R steam:steam /var/lib/steam /var/log/steam && \
  steamcmd +login anonymous +quit && \
  rm -rf /var/lib/steam/Steam/logs && \
  ln -sf /var/log/steam /var/lib/steam/Steam/logs
