FROM webhippie/ubuntu:20.04-amd64@sha256:ba3491fef0a6208b113e39bcde2e132152a5d87b073bc70dc5c19c86a0ff1b93

WORKDIR /var/lib/steam

RUN apt-get update -y && \
  apt-get upgrade -y && \
  apt-get install -y locales lib32gcc1 && \
  dpkg --add-architecture i386 && \
  locale-gen en_US.UTF-8 && \
  mkdir -p /var/lib/steam /var/log/steam && \
  groupadd -g 1000 steam && \
  useradd -u 1000 -d /var/lib/steam -g steam -s /bin/bash -M steam && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

COPY ./overlay /

RUN curl http://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz | tar -C /var/lib/steam -xzf - && \
  chown -R steam:steam /var/lib/steam /var/log/steam && \
  steamcmd +login anonymous +quit && \
  rm -rf /var/lib/steam/Steam/logs && \
  ln -sf /var/log/steam /var/lib/steam/Steam/logs
